Semana2Hackaton/README.md
=> Pull request desde linux

Semana2Hackaton/README.md
=> commit de jacqueline

Semana2Hackaton/virtual/emadrid/nombre.md
=> Commit Hackathon S2

.vscode/settings.json, Semana2Hackaton/virtual/README.md, Semana2Hackaton/virtual/loyola/nombre.md
=> pull request lorena

Semana2Hackaton/README.md, Semana2Hackaton/virtual/mfiorella/nombre.md
solicitud de pullrequest a la rama de desarrollo (carpeta con nombre)
=> pullrequest de fiorella

Semana2Hackaton/virtual/sperez/nombre.md
Commit Sergio Perez 2 - entrega de trabajo en clase
=> Commit Sergio Perez 2

.vscode/settings.json, Semana2Hackaton/README.md, Semana2Hackaton/virtual/README.md, Semana2Hackaton/virtual/bporras/readme.md, Semana2Hackaton/virtual/dgarcia/nombre.md, Semana2Hackaton/virtual/emadrid/nombre.md, Semana2Hackaton/virtual/loyola/nombre.md, Semana2Hackaton/virtual/mfiorella/nombre.md, Semana2Hackaton/virtual/rpineda/nombre.md, Semana2Hackaton/virtual/sperez/nombre.md, Semana2Sesion3/README.md
Pull Request 2 rcornejo Hackaton2
=> Pull Request 2 rcornejo

Semana2Hackaton/virtual/Berlanga/nombre.md
Mi carpeta Braulio Berlanga "Este es mi pull request"
=> Pull request

Semana2Hackaton/virtual/asalas/asalas.md
Mi primer pull request calificado  :)
=> pull request Anival Salas

Semana2Hackaton/virtual/rcornejo/nombre.md
Pull request calificado rcornejo 2
=> Pull request calificado rcornejo 2

Semana2Hackaton/virtual/ricarvell/nombre.md
=> intento 2000

Semana2Hackaton/README.md, Semana2Hackaton/virtual/hvasquez/nombre.md
Solicitud de Pull Request a la rama de desarrollo de RPineda
=> Pull Request de Hipolito V

Semana2Hackaton/virtual/lcolan/pruebalen.md
Mi primer pull request / Lennard
=> pull request rpineda

Semana3Sesion3/asalas/productos_asalas.py
=> Programa Agrega, ELimina e Inventario de Productos att. asalas

Semana3Hackaton/bberlangas/Inventario.py
Envio de tarea del inventario HacktonSemana3
=> Commit_1_enviodelatarea

Semana3Hackaton/ezagastizabal/HackatonS3.py, Semana3Hackaton/ezagastizabal/Pruebas.py, Semana3Hackaton/ezagastizabal/Readme.md
Pull request: Edwin Zagastizábal
=> Hackaton Semana 3 - Programa Inventario - Edwin Zagastizábal

Semana4Hackaton/bberlanga/Inventario.py, Semana4Sesion1/rpineda/utils.py
Hackato_4_inventario bberlanga
=> Committ_hackato_4

.vscode/settings.json, Semana3Hackaton/wquispe/jquispe.py
Ingeniero; pude arreglar el problema del visual studio code; ya aparecio el archivo en mi repositorio remoto; le envío este pull request para actualizar la carpeta de la 3ra Hackathon, gracias.
=> Jorge Quispe

Semana3Hackaton/fmilla/programa.py
Creo que envié el otro pullrequest vacío
=> Semana3Hackaton

Semana4Hackaton/emadrid/inventario.py, Semana4Hackaton/emadrid/utils.py
=> Hackathon Semana 4

.vscode/settings.json, Semana4Hackaton/ezagastizabal/Hackaton.py
=> HackatonS4

Semana5Hackaton/emadrid/crearTablasMySQL.sql, Semana5Hackaton/emadrid/crearTablasPostgreSQL.sql, Semana5Hackaton/emadrid/crudAlumno.sql, Semana5Hackaton/emadrid/crudNotas.sql, Semana5Hackaton/emadrid/crudProfesor.sql, Semana5Hackaton/emadrid/crudSalon.sql, Semana5Hackaton/emadrid/crudSemestre.sql
Tarea Hackathon 5 - BD - CRUD - PostgreSQL - MySQL
Saludos
Erin Madrid
=> Hackathon 5 - BD - CRUD - PostgreSQL - MySQL

Semana5Hackaton/ezagastizabal/crud_mysql.sql, Semana5Hackaton/ezagastizabal/crud_postgres.sql, Semana5Hackaton/ezagastizabal/db_mysql.sql, Semana5Hackaton/ezagastizabal/db_postgres.sql
Nombre: Edwin Zagastizábal
Profesor, cree la base de datos con líneas de código, por eso es algo distinto al que mostró en clase.
=> Hackaton - Base de datos

Clientes.txt, Semana4Hackaton/Sperez/Init.py, app.log
=> Hackaton semana 4 - Sergio Perez

Semana4Sesion1/asalas/init.py
=> CRUD Inventario- asalas

Semana5Hackaton/martinperez/crud-mysql.sql, Semana5Hackaton/martinperez/crud-postgres.sql, Semana5Hackaton/martinperez/mysql-martinPerez-crearBaseDatos.sql, Semana5Hackaton/martinperez/postgres-martinPerez-crearBaseDatos.sql
ENVIO LOS ARCHIVOS EN .SQL DE:
- CREACION DE BASE DE DATOS EN MYSQL Y POSTGRES
- CRUD EN MYSQL Y POSTGRES
=> MARTIN PEREZ - SEMANA 5 HACKATON

Semana5Hackaton/psanchez/Hackathon5.sql
=> Hackathon 5 - Paola Sanchez

Semana5Hackaton/bberlanga/MySQL-colegio.sql, Semana5Hackaton/bberlanga/Postgres.sql
=> Commit_sql

Semana5Hackaton/JQUISPE/CrearModelo.sql, Semana5Hackaton/JQUISPE/CrearModeloPSQL.sql, Semana5Hackaton/JQUISPE/crudPSQL.sql, Semana5Hackaton/JQUISPE/crudSQL.sql
=> "BASES DE DATOS"

Semana5Hackaton/avellaneda/errorLog.txt, Semana5Hackaton/avellaneda/modAvellaneda.sql
Profesor, el pgAdmin4 me pide un host name y otros parámetros que por el hecho de usar linux se me está complicando el simple hecho de crear una base de datos en postgres, si me puede ayudar con esto o darme un poco mas de tiempo le agradecería.
=> hackathon#5

Semana6Hackaton/JQUISPE/app/init.py, Semana6Hackaton/JQUISPE/app/prueba.py, Semana6Hackaton/JQUISPE/app/prueba2.py
Inge; le adjunto mi código para la creación de la factura; se ha llegado al objetivo de crear la factura  (tanto la tabla de Factura Cabecera y Factura Detalle).
Gracias por el tiempo dado, para la presentación.
=> "Factura creada"

Semana8Hackaton/jquispe/views/prestamos.py, Semana8Hackaton/jquispe/views/registros.py
Profesor, buenas noches; hice modificaciones en mi programa de sistema de bibliotecas; en la anterior presentación, no llegue a concluir el programa; en este intento; he llegado a lo que se quiere en la hackathon "Hacer los CRUD respectivo y hacer los registros de prestamos y devoluciones"
=> "Cambios en el programa-biblioteca"
